### ISSUE TITLE
Hot reload in real device

### ISSUE THREAD

**Issue by ghost** [bunistack/awesome-apps-with-qt-and-felgo#1]
hi bro, I'm a beginer learn felgo, how can run repo hot reload with a real device? I try to follow the documentation of felgo but it isn't running. I'm using android. thanks

**Comment by herbertamukhuma** [comment]
I have never tried it, but there is a Felgo app you need to download on your device. Check if this link helps: https://felgo.com/qml-hot-reload-for-qt-with-felgo-live
